spring.datasource.url=jdbc:mysql://localhost:3306/creatorhub
spring.datasource.username=root
spring.datasource.password=Baapkobhej#123._#

#Database driver class name
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#jpa/hibernate Auto create/update database tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Server port
server.port=8085


//Razorpay
razorpay.key.id=rzp_test_SyhyMslzCo2vDT
razorpay.key.secret=C0oQ1I7ZKa1DdU8pxLx0phg5


spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
