spring.profiles.active=local

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/creatorhub}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8085

# Razorpay Configuration
razorpay.key.id=${RAZORPAY_KEY_ID:}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
